schema_version: 1

context:
  name: lfortran
  version: 0.60.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ./..

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake =3.29.6
    - if: unix
      then: make =4.4.1
    - if: build_platform != target_platform
      then: zstd-static =1.5.6
    - nodejs
  
  host:
    - xeus =5.1.0
    - xeus-zmq =3.0.0
    - llvmdev =21.1.2
    - if: linux
      then: libunwind =1.7.2
    - nlohmann_json =3.11.3
    - zlib
    - zstd-static =1.5.7
  
  run:
    - if: win
      then: ${{ pin_compatible("xeus", upper_bound="x.x.x") }}
    - if: win
      then: zstd =1.5.6

tests:
  - requirements:
      run:
        - jupyter
    script:
      - if: win
        then: if not exist %LIBRARY_PREFIX%\bin\lfortran.exe exit 1
      - lfortran --help
      - lfortran --version
      - jupyter kernelspec list --json

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Modern interactive LLVM-based Fortran compiler
  description: |
    LFortran is a modern open-source (BSD licensed) interactive Fortran
    compiler built on top of LLVM. It can execute user's code interactively to
    allow exploratory work (much like Python, MATLAB or Julia) as well as
    compile to binaries with the goal to run user’s code on modern
    architectures such as multi-core CPUs and GPUs.
  homepage: https://lfortran.org
  repository: https://github.com/hydrolog/lfortran
  documentation: https://docs.lfortran.org/

extra:
  recipe-maintainers:
    - certik
    - Shaikh-Ubaid
    - nilocj

