[workspace]
name = "lfortran"
version = "0.60.0"
description = "Modern interactive LLVM-based Fortran compiler"
authors = ["LFortran Maintainers <lfortran@groups.io>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "linux-aarch64"]

# feature.default.tasks
[tasks]
start = {cmd = "pixi shell -e llvm21 && lfortran"}
clean = "git clean -dfx -e '.pixi'"
lfnb = {cmd = "pixi shell -e llvm21 && jupyter-lab"}

[activation.env]
CC = "clang"
CXX = "clang++"
INSTALL_DIR = "$CONDA_PREFIX"
BUILD_DIR = "build"

[feature.test.tasks]
ctest = "cmake --build $BUILD_DIR --parallel --target test"

[feature.llvm19.dependencies]
llvmdev = ">=19.1.4,<20"
clang = "==19.1.7"
clangxx = "==19.1.7"
shell = ">=0.2.0,<0.3"
[feature.llvm20.dependencies]
llvmdev = ">=20.1.8,<21"
[feature.llvm21.dependencies]
llvmdev = ">=21.1.2,<22"
clang = "==21.1.8"
clangxx = "==21.1.8"
shell = ">=0.2.0,<0.3"

[feature.llvm19.target.linux-64.dependencies]
libunwind = ">=1.8.3,<2"
[feature.llvm19.target.linux-aarch64.dependencies]
libunwind = ">=1.8.3,<2"

[feature.llvm20.target.linux-64.dependencies]
libunwind = ">=1.8.3,<2"
[feature.llvm20.target.linux-aarch64.dependencies]
libunwind = ">=1.8.3,<2"

[feature.llvm21.target.linux-64.dependencies]
libunwind = ">=1.8.3,<2"
[feature.llvm21.target.linux-aarch64.dependencies]
libunwind = ">=1.8.3,<2"

[feature.build.dependencies]
pytest = ">=9.0.2,<10"
jupyter = ">=1.1.1,<2"
xeus = ">=5.2.8,<6"
xeus-zmq = ">=3.1.2,<4"
nlohmann_json = ">=3.12.0,<4"
jupyter_kernel_test = ">=0.7.0,<0.8"
numpy = ">=2.4.2,<3"
rapidjson = ">=1.1.0.post20240409,<2"
zlib = ">=1.2.13,<2"
zstd-static = ">=1.5.6,<2"
python = ">=3.12,<3.13"
cmake = ">=3.29,<5"
ninja = ">=1.13.2,<2"
re2c = ">=4.4,<5"

[dependencies]
python = ">=3.12,<3.15"
toml = ">=0.10.2,<0.11"
pandoc = ">=3.9,<4"
ninja = ">=1.13.2,<2"

[feature.test.dependencies]
python = ">=3.12,<3.15"
toml = ">=0.10.2,<0.11"
cmake = ">=3.29,<5"
ninja = ">=1.13.2,<2"

[feature.build.target.unix.dependencies]
bison = "==3.4"

[feature.build.target.win.dependencies]
m2-bison = "==3.0.4"

[feature.build.target.linux-64.dependencies]
bison = ">=3.8.2,<4"

[feature.build.target.win-64.dependencies]
m2-bison = ">=3.0.4,<4"
xonsh = ">=0.22.4,<0.23"

[feature.build.target.linux-aarch64.dependencies]
bison = ">=3.8.2,<4"

[feature.build.target.win-64.tasks] 
build = { cmd = "cmd /k build.bat", cwd = ".", depends-on = "clean" }

[feature.build.tasks]
build = { cmd = "./build0.sh && ./build1.sh", cwd = ".", depends-on = "clean" }
sh-llvm21 = { cmd = "pixi install -e llvm21 && pixi shell -e llvm21"}
sh-llvm20 = { cmd = "pixi install -e llvm20 && pixi shell -e llvm20"}
sh-llvm19 = { cmd = "pixi install -e llvm19 && pixi shell -e llvm19"}
install = { cmd = "cmake --install $BUILD_DIR"}
integration_tests = { cmd = "./run_tests.py -j16 -b llvm --ninja", cwd = "integration_tests", depends-on = "install" }
tests = { cmd = "./run_tests.py", cwd = "." }
ci = { cmd = "./ci/build.sh" , cwd = ".", depends-on = "clean" }

[environments]
llvm19 = {features = ["llvm19", "build"]}
llvm20 = {features = ["llvm20", "build"]}
llvm21 = {features = ["llvm21", "build"]}
test = {features = ["test", "llvm21"]}
