schema_version: 1

context:
  name: lfortran
  version: 0.60.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: .
 #   branch: fix_iso_c_binding 
    # This must be in sync with build.sh:
#    git: https://github.com/emscripten-core/emsdk.git
 #   rev: 3.1.59
 #   target_directory: emsdk

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
   # - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  #  - ${{ stdlib("c") }}
    - cmake =3.29.6
    - if: unix
      then: make =4.4.1
    - if: build_platform != target_platform
      then: xeus =5.1.0
    - if: build_platform != target_platform
      then: xeus-zmq =3.0.0
    - if: build_platform != target_platform
      then: llvmdev =19.1.1
    - if: build_platform != target_platform
      then: nlohmann_json =3.11.3
    - if: build_platform != target_platform
      then: zlib
    - if: build_platform != target_platform
      then: zstd-static =1.5.6
    - nodejs
  host:
    - xeus =5.1.0
    - xeus-zmq =3.0.0
    - llvmdev =21.1.2
    - if: linux
      then: libunwind =1.7.2
    - nlohmann_json =3.11.3
    - zlib
    - zstd-static =1.5.7
  run:
    # xeus breaks abi compatibility in patch versions even though
    # run_exports say otherwise in https://github.com/conda-forge/xeus-feedstock/blob/0896038be810da2944ebcb612e22886815ea691e/recipe/meta.yaml#L18
    - if: linux
      then: libunwind =1.7.2
    - if: win
      then: ${{ pin_compatible("xeus", upper_bound="x.x.x") }}
    - if: win
      then: zstd =1.5.6

tests:
  - requirements:
      run:
        - jupyter
    script:
      - if: unix
        then: ./test_lfortran_cmdline
      - if: win
        then: if not exist %LIBRARY_PREFIX%\bin\lfortran.exe exit 1
      - lfortran --help
      - lfortran --version
      - jupyter kernelspec list --json
      - jupyter kernelspec remove -f fortran

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Modern interactive LLVM-based Fortran compiler
  description: |
    LFortran is a modern open-source (BSD licensed) interactive Fortran
    compiler built on top of LLVM. It can execute user's code interactively to
    allow exploratory work (much like Python, MATLAB or Julia) as well as
    compile to binaries with the goal to run user’s code on modern
    architectures such as multi-core CPUs and GPUs.
  homepage: https://lfortran.org
  repository: https://github.com/hydrolog/lfortran
  documentation: https://docs.lfortran.org/

extra:
  recipe-maintainers:
    - certik
    - Shaikh-Ubaid
    - nilocj

