export LFORTRAN_LINKER=gcc
export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}
export LFORTRAN_CMAKE_GENERATOR=Ninja
export ENABLE_RUNTIME_STACKTRACE=yes

#export LIBUNWIND_INCLUDE_DIR=${CONDA_PREFIX}/include
#export LIBUNWIND_LIBRARY=${CONDA_PREFIX}/lib
